dist: trusty
sudo: false

language: node_js
node_js:
- 12
env:
  - SFTP_IP=94.130.211.59

addons:
  chrome: stable
cache:
  directories:
  - "./node_modules"
install:
- npm install
script:
- npm run test -- --watch=false --no-progress --browsers=ChromeHeadlessNoSandbox
before_install:
- openssl aes-256-cbc -K $encrypted_dfdcfd5172af_key -iv $encrypted_dfdcfd5172af_iv
  -in deploy_key.enc -out ./deploy_key -d
- eval "$(ssh-agent -s)"
- chmod 600 ./deploy_key
- echo -e "Host $SFTP_IP\n\tStrictHostKeyChecking no\n" >> ~/.ssh/config
- ssh-add ./deploy_key
- ssh -i ./deploy_key andreev_work@94.130.211.59
